In [1]:
from sklearn.datasets import load_diabetes

import numpy as np

In [2]:
X, y = load_diabetes(return_X_y=True)

In [17]:
X.shape

(442, 10)

In [12]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=42)

In [9]:
lr = LinearRegression()

In [10]:
lr.fit(X_train, y_train)

LinearRegression()

In [11]:
y_pred = lr.predict(X_test)

In [14]:
lr.coef_

array([  37.90402135, -241.96436231,  542.42875852,  347.70384391,
       -931.48884588,  518.06227698,  163.41998299,  275.31790158,
        736.1988589 ,   48.67065743])

In [15]:
lr.intercept_

151.34560453985995

In [13]:
r2_score(y_test, y_pred)

0.4526027629719196

#### Now doing everything with SGDRegressor

In [19]:
from sklearn.linear_model import SGDRegressor

In [20]:
sgd = SGDRegressor(max_iter=100, learning_rate='constant', eta0=0.01)

In [21]:
sgd.fit(X_train, y_train)

C:\Users\PK419HT\AppData\Local\anaconda3\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(learning_rate='constant', max_iter=100)

In [22]:
sgd.coef_

array([ 5.68854915e+01, -9.04693694e+01,  3.58997245e+02,  2.47964156e+02,
        8.75562946e-02, -3.66818978e+01, -1.80751150e+02,  1.47625636e+02,
        2.83459005e+02,  1.47258204e+02])

In [23]:
sgd.intercept_

array([150.69258818])

In [24]:
y_pred2 = sgd.predict(X_test)

In [26]:
r2_score(y_test, y_pred2)

0.44579879573770753