In [1]:
from sklearn.datasets import make_classification

In [2]:
df = make_classification(n_features=2, n_samples=100, n_informative=1,n_redundant=0,n_classes=2, 
                         n_clusters_per_class=1, random_state=41,hypercube=False,class_sep=10)

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
df

(array([[ 0.19924745, -0.11697552],
        [-0.24882029, -0.73115232],
        [-0.3544904 , -0.7081059 ],
        [-1.59086506, -2.01199214],
        [-0.20083951,  1.63493163],
        [-0.83241122,  0.15599044],
        [-1.79207014,  1.07782053],
        [ 0.0856607 ,  0.80626713],
        [-0.55865299,  0.74859527],
        [-1.95974262,  0.75152794],
        [-1.77828947, -0.90114581],
        [-1.77985853, -0.1815243 ],
        [-0.02194151, -2.98092432],
        [ 0.80563431,  1.20500136],
        [-1.82701214,  0.78302407],
        [ 0.38730728,  0.42968688],
        [-0.14108668, -0.73229726],
        [-1.87955941, -0.83930476],
        [-0.18232911,  0.83727062],
        [-1.77059533, -0.10255323],
        [-2.27658028,  0.65867001],
        [-2.06519502,  0.92649819],
        [-1.31690551,  0.10216193],
        [ 1.61043259,  0.46886454],
        [-1.21650394,  0.45432938],
        [ 0.6139723 ,  1.8613386 ],
        [-1.78760957, -0.79255991],
        [-1.04149161, -1.000

In [10]:
type(df)

tuple

In [12]:
df[0]

array([[ 0.19924745, -0.11697552],
       [-0.24882029, -0.73115232],
       [-0.3544904 , -0.7081059 ],
       [-1.59086506, -2.01199214],
       [-0.20083951,  1.63493163],
       [-0.83241122,  0.15599044],
       [-1.79207014,  1.07782053],
       [ 0.0856607 ,  0.80626713],
       [-0.55865299,  0.74859527],
       [-1.95974262,  0.75152794],
       [-1.77828947, -0.90114581],
       [-1.77985853, -0.1815243 ],
       [-0.02194151, -2.98092432],
       [ 0.80563431,  1.20500136],
       [-1.82701214,  0.78302407],
       [ 0.38730728,  0.42968688],
       [-0.14108668, -0.73229726],
       [-1.87955941, -0.83930476],
       [-0.18232911,  0.83727062],
       [-1.77059533, -0.10255323],
       [-2.27658028,  0.65867001],
       [-2.06519502,  0.92649819],
       [-1.31690551,  0.10216193],
       [ 1.61043259,  0.46886454],
       [-1.21650394,  0.45432938],
       [ 0.6139723 ,  1.8613386 ],
       [-1.78760957, -0.79255991],
       [-1.04149161, -1.0004391 ],
       [-2.40067584,

In [15]:
df[0][0]

array([ 0.19924745, -0.11697552])

In [18]:
import numpy as np

In [25]:

for i in df:
    for j in i:
        np.append(x1,j[0])
        np.append(x2,j[1])

IndexError: invalid index to scalar variable.

In [21]:
x1 = np.array([])
x2 = np.array([])

In [46]:
for i in df:
    for j in i:
        for z in range(0,len(j)-1):
            print(j[z])

0.1992474462416376
-0.24882028768794578
-0.3544903959655015
-1.590865062356334
-0.20083950504878806
-0.8324112198271086
-1.7920701402317816
0.08566069951852703
-0.5586529929016766
-1.9597426224264232
-1.778289474413809
-1.7798585331817427
-0.021941511996591057
0.8056343099031197
-1.827012138309396
0.3873072795803456
-0.1410866755296707
-1.8795594059181007
-0.18232911351610126
-1.7705953279961077
-2.276580284939673
-2.0651950213115615
-1.3169055101844445
1.6104325935502295
-1.2165039378374554
0.613972301079603
-1.7876095659527698
-1.0414916146943165
-2.400675837186087
-1.8038345223304737
-1.4407561318208204
1.3498997776790105
0.22520166941694947
0.5368852675714689
0.5548345863192292
-0.32178184655120984
-0.9882124767230576
0.6739480453775373
-1.6091359159370813
0.7572719385308917
-1.3259137604190419
-0.9178329263749654
-1.3557814669718056
1.468696586185109
-0.8054071306379358
1.080598160238745
0.1466732645708569
-1.3732454797397589
-1.0974208934486926
-0.9201747642005302
0.2202051295706

TypeError: object of type 'numpy.int32' has no len()

In [42]:
a = [10, 20, 30, 40]

In [43]:
for i in range(len(a)):
    print(a[i])

10
20
30
40
